### ISSUE TITLE
Question: SAP BTP REST API + Launchpad Srv + Destination

### ISSUE THREAD

**Issue by kevindass** [nicoschoenteich/nicoschoenteich#1]
Nico,

I have being working on SAP-samples
/multi-cloud-html5-apps-samples for a while now. It has given me a better understanding with apps in different flavors on BTP-CF.

We all start with Northwind Odata and all goes well. However I did explore REST API example https://reqres.in/ and it works well while running on SAP BAS. However when deployed on CF and configured on Launchpad Service it has issues connecting to destination.

I did a lot of reading on SAP blogs and also did review [Integrate the REST API via Destination Service](https://help.sap.com/docs/CP_FORMS_BY_ADOBE/dcbea777ceb3411cb10500a1a392273e/051d651b628c496c86bd1d4f95d718fc.html)
 
I have posted question as well https://answers.sap.com/questions/13761787/sap-btp-launchpad-services-integrate-the-rest-api.html

I would highly appreciate if you could assist me here.

Regards,
Kevin Dass

**Comment by nicoschoenteich** [comment]
Hi @kevindass, I [replied to the thread](https://answers.sap.com/answers/13764332/view.html) on answers.sap.com. Hope it helps. Best, Nico
